server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: restaurant-api

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_management_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Africa/Casablanca
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

app:
  jwt:
    secret: "CHANGE_THIS_SECRET_KEY_TO_A_LONG_SECURE_VALUE_FOR_PRODUCTION"
    expiration-ms: 28800000

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG